import { Helmet } from "react-helmet-async";
const markets = [
 ["Government","Govern autonomous execution across public institutions with continuously verifiable authority, accountability, evidence, and human control."],
 ["Financial Services","Enable governed autonomous execution where fiduciary duty, auditability, operational resilience, and regulatory accountability are institutional requirements."],
 ["Healthcare","Apply Trust Infrastructure to autonomous workflows where privacy, authorization, accountability, and durable evidence are essential."],
 ["Critical Infrastructure","Preserve institutional control across autonomous systems in high-consequence environments where resilience, provenance, authorization, and assurance cannot be optional."],
 ["Energy","Govern autonomous decision and execution across complex energy environments with explicit authority boundaries, continuous assurance, and verifiable institutional accountability."],
 ["Enterprise","Give large organizations an institutional architecture for delegating execution to autonomous systems without surrendering governance, accountability, or control."]
];
export default function MarketsWeServePage(){return <><Helmet><title>Markets We Serve | CoreIdentity Development Group</title><meta name="description" content="CoreIdentity serves institutions operating under significant regulatory, fiduciary, and operational obligations."/></Helmet><main className="cidg-markets-page"><section className="cidg-markets-hero"><p className="cidg-markets-kicker">Markets We Serve</p><h1>Governance for institutions where autonomy carries consequence.</h1><p>CoreIdentity serves institutions operating under significant regulatory, fiduciary, and operational obligations—enabling them to delegate autonomous execution with verifiable trust, accountability, authority, and control.</p></section><section className="cidg-markets-grid" aria-label="CoreIdentity markets">{markets.map(([title,body])=><article key={title}><h2>{title}</h2><p>{body}</p></article>)}</section><section className="cidg-markets-close"><p className="cidg-markets-kicker">The Institutional Standard</p><h2>Delegate Execution. Never Surrender Control.</h2><p>The Governance Ecosystem is designed for environments in which governance failure carries material institutional consequences.</p></section></main></>}
