// =============================================================================
// CoreIdentity — Build-time version attestation
// Generated by 01-version-attestation.sh. Do not hand edit.
//
// Runs as npm `postbuild`. Emits <outDir>/version.json so production can be
// verified by identity rather than by inference.
//
// Commit resolution order:
//   1. CF_PAGES_COMMIT_SHA  (Cloudflare Pages build environment)
//   2. git rev-parse HEAD   (works on Cloudflare too — Pages clones at the
//                            target commit — and locally)
//   3. "unknown"            (never silently omitted)
// =============================================================================
import { execSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const sh = (cmd) => {
  try {
    return execSync(cmd, { stdio: ["ignore", "pipe", "ignore"] }).toString().trim();
  } catch {
    return "";
  }
};

const commit =
  process.env.CF_PAGES_COMMIT_SHA || sh("git rev-parse HEAD") || "unknown";
const branch =
  process.env.CF_PAGES_BRANCH || sh("git rev-parse --abbrev-ref HEAD") || "unknown";
const tag = sh("git describe --tags --exact-match 2>/dev/null") || null;

const outDir = resolve(process.cwd(), process.env.BUILD_DIR || "dist");
if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

const payload = {
  schema: 1,
  commit,
  commitShort: commit === "unknown" ? "unknown" : commit.slice(0, 7),
  branch,
  tag,
  builtAt: new Date().toISOString(),
  builder: process.env.CF_PAGES_COMMIT_SHA ? "cloudflare-pages" : "local",
  node: process.version,
};

const target = resolve(outDir, "version.json");
writeFileSync(target, JSON.stringify(payload, null, 2) + "\n", "utf8");
console.log(`version attestation -> ${target} (${payload.commitShort})`);

if (commit === "unknown") {
  console.error("WARNING: commit could not be resolved. Attestation is not verifiable.");
  process.exit(1);
}
